name: Build makedeb
on: {"pull_request"}
env: {"DEBIAN_FRONTEND": "noninteractive"}
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: proget.hunterwittenborn.com/docker/makedeb/makedeb-alpha:ubuntu-focal
      options: --user makedeb
    steps:
      - name: Install CI prerequisites
        run: sudo -E apt-get install git -y

      - name: Check user
        run: |
          echo "$(whoami) ${PWD}"
          ls -alF ./ ../

      - name: Checkout Git repository
        run: git clone "${{ github.server_url }}/${{ github.repository }}" -b "${{ github.head_ref }}"

      - name: Install needed dependencies
        working-directory: ./makedeb
        run: .drone/scripts/install-deps.sh
      
      - name: Run unit tests
        working-directory: ./makedeb
        run: release_type="${GITHUB_BASE_REF}" .drone/scripts/run-unit-tests.sh

# vim: expandtab ts=2 sw=2
