name: Build makedeb
on:
 pull_request:
jobs:
  build:
    runs-on: 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker://proget.hunterwittenborn.com/docker/makedeb/makedeb-alpha:ubuntu-focal
        run: |
          export DEBIAN_FRONTEND=noninteractive release_type=alpha pkgname=makedeb-alpha
          sudo -E apt-get install tzdata git jq sudo sed ubuntu-dev-tools debhelper asciidoctor -y
          sudo chown 'makedeb:makedeb' ../ -R
          .drone/scripts/build-native.sh
      - name: Move built .deb to current directory
        run: mv -v ../*.deb ./makedeb.deb
      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: makedeb-native-build
          path: "makedeb.deb"
