name: Build makedeb
on:
 pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y git gnupg pbuilder ubuntu-dev-tools apt-file python3 python3-pip debhelper asciidoctor jq
      - name: add VERSION env var
        run: |
          cat << EOF > .env
          VERSION=$(cat .data.json | jq -r '.current_pkgver')
          EOF
      - name: tar directory into source tarball
        run: source .env && tar -cJf ../makedeb_$VERSION.orig.tar.xz .
      - name: build makedeb using native packaging
        run: source .env && ls .. && debuild -us -uc
      - name: Move artifact to current dir
        run: mv -v ../*.deb ./makedeb.deb
      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: makedeb-native-build
          path: "makedeb.deb"
