name: Build makedeb
on:
 pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: proget.hunterwittenborn.com/docker/makedeb/makedeb-alpha:ubuntu-focal
    steps:
      - name: Set directory permissions
        run: sudo chown 'makedeb:makedeb' ../ -R
      - name: Install needed dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo -E apt-get install tzdata git jq sudo sed ubuntu-dev-tools debhelper asciidoctor bats -y
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head_sha }}

      - name: Run unit tests
        run: .drone/scripts/run-unit-tests.sh

# vim: expandtab ts=2 sw=2
