name: Build makedeb
on: {"pull_request"}
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: proget.hunterwittenborn.com/docker/makedeb/makedeb-alpha:ubuntu-focal
      options: --user root
    env:
      DEBIAN_FRONTEND: "noninteractive"
      makedeb_url: "makedeb.org"
    steps:
      - name: Install CI prerequisites
        run: apt-get install git -y

      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          path: ./makedeb

      - name: Ensure directory permissions are correct
        run: |
          chown 'makedeb:makedeb' /__w /home -R
          find /__w /home -type d -exec chmod a+rwx '{}' +
          find /__w /home -type f -exec chmod a+rw '{}' +


      - name: Install needed dependencies
        working-directory: ./makedeb
        # For some reason we need to include this 'makedeb_url=' declaration, not sure why yet.
        run: makedeb_url="${makedeb_url}" .drone/scripts/install-deps.sh
      
      - name: Run unit tests
        working-directory: ./makedeb
        run: |
          . "$HOME/.cargo/env"

          # REMOVE BEFORE MERGING!!!
          echo "${PATH}" &> /dev/stderr

          sudo -Eu makedeb release_type="${GITHUB_BASE_REF}" makedeb_url="${makedeb_url}" .drone/scripts/run-unit-tests.sh

# vim: expandtab ts=2 sw=2
