name: Build makedeb
on: {"pull_request"}
env:
  DEBIAN_FRONTEND: "noninteractive"
  makedeb_url: "makedeb.org"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: proget.hunterwittenborn.com/docker/makedeb/makedeb-alpha:ubuntu-focal
      options: --user root
    steps:
      - name: Install CI prerequisites
        run: apt-get install git -y

      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          path: ./makedeb

      - name: Ensure directory permissions are correct
        run: |
          sudo chown 'makedeb:makedeb' /__w /home -R
          find /__w /home -type d -exec sudo chmod a+rwx '{}' +
          find /__w /home -type f -exec sudo chmod a+rw '{}' +


      - name: Install needed dependencies
        working-directory: ./makedeb
        run: .drone/scripts/install-deps.sh
      
      - name: Run unit tests
        working-directory: ./makedeb
        run: sudo -u makedeb release_type="${GITHUB_BASE_REF}" .drone/scripts/run-unit-tests.sh

# vim: expandtab ts=2 sw=2
