name: Build makedeb
on:
 pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: proget.hunterwittenborn.com/docker/makedeb/makedeb:ubuntu-focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "makedeb"
      - name: Generate PKGBUILD and build with makedeb
        run: |
          sudo chown -R makedeb:makedeb .
          sudo apt update && sudo apt install -y git jq
          cd PKGBUILD
          ./pkgbuild.sh > PKGBUILD
          PACMAN='/usr/bin/true' makedeb -s --no-confirm
        env:
          TARGET: local
          RELEASE: alpha

  build-native:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y git gnupg pbuilder ubuntu-dev-tools apt-file python3 python3-pip debhelper asciidoctor jq
      - name: add VERSION env var
        run: |
          cat << EOF > .env
          VERSION=$(cat .data.json | jq -r '.current_pkgver')
          EOF
      - name: tar directory into source tarball
        run: source .env && tar -cJf ../makedeb_$VERSION.orig.tar.xz .
      - name: build makedeb using native packaging
        run: source .env && ls .. && debuild -us -uc
